package hewson.logindemo2.vo;


import java.io.Serializable;
import java.util.Date;

public class UserVo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.UserId
     *
     * @mbg.generated
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.T_Email
     *
     * @mbg.generated
     */
    private String tEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.T_Avator
     *
     * @mbg.generated
     */
    private String tAvator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.T_Balance
     *
     * @mbg.generated
     */
    private Double tBalance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.T_Sex
     *
     * @mbg.generated
     */
    private String tSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.T_Birthday
     *
     * @mbg.generated
     */
    private Date tBirthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.T_Tell
     *
     * @mbg.generated
     */
    private String tTell;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.T_isDestroy
     *
     * @mbg.generated
     */
    private Boolean tIsdestroy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.T_DeadTime
     *
     * @mbg.generated
     */
    private Date tDeadtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.UserId
     *
     * @return the value of t_user.UserId
     *
     * @mbg.generated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.UserId
     *
     * @param userid the value for t_user.UserId
     *
     * @mbg.generated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.username
     *
     * @return the value of t_user.username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.username
     *
     * @param username the value for t_user.username
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.password
     *
     * @return the value of t_user.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.password
     *
     * @param password the value for t_user.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.T_Email
     *
     * @return the value of t_user.T_Email
     *
     * @mbg.generated
     */
    public String gettEmail() {
        return tEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.T_Email
     *
     * @param tEmail the value for t_user.T_Email
     *
     * @mbg.generated
     */
    public void settEmail(String tEmail) {
        this.tEmail = tEmail == null ? null : tEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.T_Avator
     *
     * @return the value of t_user.T_Avator
     *
     * @mbg.generated
     */
    public String gettAvator() {
        return tAvator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.T_Avator
     *
     * @param tAvator the value for t_user.T_Avator
     *
     * @mbg.generated
     */
    public void settAvator(String tAvator) {
        this.tAvator = tAvator == null ? null : tAvator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.T_Balance
     *
     * @return the value of t_user.T_Balance
     *
     * @mbg.generated
     */
    public Double gettBalance() {
        return tBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.T_Balance
     *
     * @param tBalance the value for t_user.T_Balance
     *
     * @mbg.generated
     */
    public void settBalance(Double tBalance) {
        this.tBalance = tBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.T_Sex
     *
     * @return the value of t_user.T_Sex
     *
     * @mbg.generated
     */
    public String gettSex() {
        return tSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.T_Sex
     *
     * @param tSex the value for t_user.T_Sex
     *
     * @mbg.generated
     */
    public void settSex(String tSex) {
        this.tSex = tSex == null ? null : tSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.T_Birthday
     *
     * @return the value of t_user.T_Birthday
     *
     * @mbg.generated
     */
    public Date gettBirthday() {
        return tBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.T_Birthday
     *
     * @param tBirthday the value for t_user.T_Birthday
     *
     * @mbg.generated
     */
    public void settBirthday(Date tBirthday) {
        this.tBirthday = tBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.T_Tell
     *
     * @return the value of t_user.T_Tell
     *
     * @mbg.generated
     */
    public String gettTell() {
        return tTell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.T_Tell
     *
     * @param tTell the value for t_user.T_Tell
     *
     * @mbg.generated
     */
    public void settTell(String tTell) {
        this.tTell = tTell == null ? null : tTell.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.T_isDestroy
     *
     * @return the value of t_user.T_isDestroy
     *
     * @mbg.generated
     */
    public Boolean gettIsdestroy() {
        return tIsdestroy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.T_isDestroy
     *
     * @param tIsdestroy the value for t_user.T_isDestroy
     *
     * @mbg.generated
     */
    public void settIsdestroy(Boolean tIsdestroy) {
        this.tIsdestroy = tIsdestroy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.T_DeadTime
     *
     * @return the value of t_user.T_DeadTime
     *
     * @mbg.generated
     */
    public Date gettDeadtime() {
        return tDeadtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.T_DeadTime
     *
     * @param tDeadtime the value for t_user.T_DeadTime
     *
     * @mbg.generated
     */
    public void settDeadtime(Date tDeadtime) {
        this.tDeadtime = tDeadtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userid=").append(userid);
        sb.append(", username=").append(username);
        sb.append(", password=").append(password);
        sb.append(", tEmail=").append(tEmail);
        sb.append(", tAvator=").append(tAvator);
        sb.append(", tBalance=").append(tBalance);
        sb.append(", tSex=").append(tSex);
        sb.append(", tBirthday=").append(tBirthday);
        sb.append(", tTell=").append(tTell);
        sb.append(", tIsdestroy=").append(tIsdestroy);
        sb.append(", tDeadtime=").append(tDeadtime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}
